#166790057 Implements liking and disliking of Articles
andela/ah-jawans-frontend pull request #42
Opened 2019-09-11 07:46 UTC by mnzube

#### What does this PR do?
This PR allows a user to like and/or dislike articles.
#### Description of Task to be completed?
- add actions and reducers
- add icons to like or dislike
- added code for the component
- introduce tests
All this will allow users to like or dislike articles,
#### How should this be manually tested?
After cloning the repository run `npm run dev`
this will redirect you to the profile page. Select an article and at the bottom of an article,
you will find a thumbs up and down icons which depict liking or disliking an article
#### What are the relevant pivotal tracker stories?
[#166790057](https://www.pivotaltracker.com/story/show/166790057)
#### Screenshots (if appropriate)

2019-09-12 15:05 UTC, shaluchandwani commented on src/redux/store/initialStates/userInitialState.js
> +  likes: {
Always add the initial state at the end, this won't create conflicts later.

2019-09-13 10:07 UTC, Joe-Joseph reviewed
Good work on your PR @mnzube, kindly adjust the like and dislike buttons to come after the article body has displayed.

2019-09-13 10:10 UTC, mnzube commented on src/redux/store/initialStates/userInitialState.js
> +  likes: {
Alright Shalu , changed this.

2019-09-13 10:13 UTC, shaluchandwani requested changes
Good work on the PR @mnzube, although I found out some issues please address them.

1. Change you commit message to finishes.
2. When I am not logged in, I cannot click on the likes and dislikes button. It should actually throw me an error that " Please login first to perform the action".

2019-09-13 10:47 UTC, kagabof approved these changes

2019-09-13 10:49 UTC, Joe-Joseph approved these changes
Good work on this @mnzube

2019-09-13 10:53 UTC, merged