166790059 Sharing article on social media
andela/ah-jawans-frontend pull request #43
Opened 2019-09-11 11:04 UTC by Joe-Joseph

#### What does this PR do?
 - Sharing article on social media
#### Description of Task to be completed?
 - Add icons on read article page for sharing article on social media
 - Make icons links to redirect to where you want to share your article
#### How should this be manually tested?
  - clone the repo
  - npm run test
  - npm run install
  - npm run dev
#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
 - [166790059](https://www.pivotaltracker.com/story/show/166790059)
#### Screenshots (if appropriate)

#### Questions:

2019-09-11 13:06 UTC, shaluchandwani requested changes
Good work on the PR @Joe-Joseph, although I noticed when you are at 100% zoom the buttons are coming with the article. Also, the commit message has incorrect finish it's not reflecting on your PT. Please correct that.

2019-09-12 07:31 UTC, shaluchandwani approved these changes
Good Work on the PR @Joe-Joseph, You implemented the changes correctly.

2019-09-12 07:48 UTC, kagabof approved these changes

2019-09-12 08:14 UTC, billkabanga commented on src/components/article/readArticle.js
> +                <h2 className='article-text title'>{this.state.title}</h2>
Great work on this PR, Please utilise object destructuring when accessing information from props or state objects.

2019-09-12 12:14 UTC, merged