#166790067: Reporting an article
andela/ah-jawans-frontend pull request #49
Opened 2019-09-15 22:12 UTC by kagabof

#### What does this PR do?

- Enables users to report articles.

#### Description of Task to be completed?

- Add actions, reducers and initial state for reporting an article.
- Add a model for reporting an article.
- Add tests for reporting articles.

#### How should this be manually tested?

- By using reporting an article.

#### What are the relevant pivotal tracker stories?

[#166790067](https://www.pivotaltracker.com/story/show/166790067)

#### Screenshots (if appropriate)

2019-09-16 07:56 UTC, shaluchandwani requested changes
Good Work on the PR @kagabof. I would be great if you will remove the border for the select buttons and text in your report article page. Also if the R is capital in report article, it will look good.

2019-09-16 08:10 UTC, kagabof commented
@shaluchandwani, well do. just add a message that indicates that you have no bookmarked articles.

2019-09-16 09:56 UTC, shaluchandwani approved these changes
Approved!

2019-09-16 10:06 UTC, pngabo approved these changes

2019-09-16 13:27 UTC, patrickngabo commented on src/assets/scss/components/articlesDownSide.scss
> +}
add a line at the end of the file

2019-09-16 13:51 UTC, Joe-Joseph approved these changes

2019-09-17 07:12 UTC, billkabanga commented
Great work on this PR, please have the content of this modal centre-aligned
<img width="1403" alt="Screenshot 2019-09-17 at 10 09 31" src="https://user-images.githubusercontent.com/40595048/65019225-7621d900-d933-11e9-9ac0-67916e161d17.png">

Also fix this, I think it should be `harassment` not `harsment`
<img width="235" alt="Screenshot 2019-09-17 at 10 07 41" src="https://user-images.githubusercontent.com/40595048/65019266-8cc83000-d933-11e9-99e2-2583ea82cd36.png">

2019-09-17 14:04 UTC, merged